language: node_js
node_js:
  - "4.1"
before_script:
  - npm install grunt-cli -g
  - npm install webdriverio -g
  - npm install jasmine -g
addons:
  sauce_connect: true
branches:
  only:
    - master
    - gh-pages
script:
  - grunt test:saucelabs
